### ISSUE TITLE
server not starting after update

### ISSUE THREAD

**Issue by antgonzo845** [AllOfFabric/All-of-Fabric-3#10]
*warning I'm a huge newb when it comes to this stuff*

I was running AOF3 1.2.0 on my server and it started to crash every time a potion was thrown. Seeing that this was fixed in a new update, I attempted to update my server to 1.2.2 and now it attempts to start but crashes and gives me this console message (linked below) https://filebin.net/l6d0aaeahyva9bz1 

Again i'm pretty tech illiterate so I have no idea what it means, but if I had to guess I set up the server jars wrong. 
I dragged fabric-server-launch.jar and server.jar to my server's main directory, renamed fabric-server-launch.jar to custom.jar and set that as my server's jar file. If anybody could help I would really appreciate it! and if you need info or screenshots don't hesitate to ask, i've got nothing to do today besides try and fix this server.

**Comment by Yoghurt4C** [comment]
remove the mousewheelie jar from your server, it should start fine
