### ISSUE TITLE
Broken manifest

### ISSUE THREAD

**Issue by ImChinaNB** [AllOfFabric/All-of-Fabric-3#13]
In the July 4th release (1.2.2), it says
  "minecraft": {
    "version": "1.15.2",
    "modLoaders": [
      {
        "id": "forge-31.1.44",
        "primary": true
      }
    ]
makes it being loaded as a 1.15.2 Forge modpack in GDLauncher.
I think it should just be a typo or something similar.

**Comment by ImChinaNB** [comment]
Sry I just be idiot

**Comment by Avakining** [comment]
What did you do to fix this? It seems to also be the issue with Twitch...
