### ISSUE TITLE
crash on launch. Imported from zip to MultiMC

### ISSUE THREAD

**Issue by AwwShoot** [AllOfFabric/All-of-Fabric-3#7]
log:
[2020-06-30-1.log.gz](https://github.com/AllOfFabric/All-of-Fabric-3/files/4853497/2020-06-30-1.log.gz)

happens on each attempt.

**Comment by AK9Official** [comment]
fixed in 1.2.1, will be out within an hour.

**Comment by AwwShoot** [comment]
poggers

**Comment by AK9Official** [comment]
@AwwShoot https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/2993236
