### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Supermatt01** [AllOfFabric/All-of-Fabric-3#9]
I got this as a rar archive. I have no clue how to install this. I don't have the twitch version nor the other type that can import rar files. Should I just put the files in to the mods folder?

**Comment by HaloSense** [comment]
No.
You can download a third-party launcher (e.g. MultiMC) and import the .rar file. After importing, simply launch the game and let the launcher do the rest.
There are a few options listed on the curseforge page.

**Comment by Supermatt01** [comment]
I use TLauncher. Is there anyway to inject it in to that one? On Jul 3, 2020 2:56 PM, HaloSense <notifications@github.com> wrote:
No.
You can download a third-party launcher (e.g. MultiMC) and import the .rar file. After importing, simply launch the game and let the launcher do the rest.
There are a few options listed on the curseforge page.
